version: "3"
networks:
  imagini:
services:
  database:
    image: mysql:5.7
    networks:
      - imagini
    volumes:
      - c:/users/unkno/study/hands-on-microservice/chapter06/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: imagini
      MYSQL_ROOT_PASSWORD: secret
  service:
    image: imagini:0.0.3
    networks:
      - imagini
    volumes:
      - c:/users/unkno/study/hands-on-microservice/chapter06/settings.json:/opt/app/settings.json
    ports:
      - "80:3000"
    restart: on-failure
